CREATE TABLE EMP(
	EMPNO INT unsigned NOT NULL,
	ENAME VARCHAR(50)NOT NULL,
	JOB VARCHAR(50) NOT NULL,
	MGR INT UNSIGNED,
	HIREDATE DATE NOT NULL,
	SAL DECIMAL(8,2)  NOT NULL,
	COMM  DECIMAL(8,2),
	DEPTNO TINYINT NOT NULL,
	CONSTRAINT CLE_EMPNO PRIMARY KEY(EMPNO));
