-- SELECT ENAME,JOB,DEPTNO FROM emp WHERE deptno IN(20,30) AND job='MANAGER';
-- SELECT * FROM emp WHERE job <> 'MANAGER' AND DATE_FORMAT(hiredate,'%y')= 81;
-- SELECT * FROM emp WHERE comm <> 0;
-- SELECT ENAME,DEPTNO,JOB,HIREDATE FROM emp ORDER BY HIREDATE DESC,DEPTNO;
-- SELECT * FROM emp INNER JOIN dept ON dept.deptno = emp.deptno WHERE LOC ='DALLAS';
SELECT ENAME,CASE WHEN JOB <>'MANAGER' AND DEPTNO =30 THEN HIREDATE WHERE 
