-- ALTER TABLE emp ADD CONSTRAINT fk_mgr_empno FOREIGN KEY (MGR) REFERENCES emp (EMPNO);
-- ALTER TABLE emp ADD CONSTRAINT fk_deptno_empno FOREIGN KEY (DEPTNO) REFERENCES dept(DEPTNO);

-- UPDATE emp SET ENAME='ALLEN' WHERE EMPNO = 7499;

-- SELECT ENAME,JOB,EMPNO,SAL FROM emp WHERE DEPTNO =10;
-- SELECT ENAME,JOB,EMPNO,SAL FROM emp WHERE JOB='MANAGER' and SAL>2800;
-- SELECT JOB FROM emp WHERE DEPTNO !=30;
-- SELECT * FROM emp WHERE SAL BETWEEN 1200 AND 1400;
-- SELECT * FROM emp  WHERE DEPTNO IN(10,30) ORDER BY ENAME;
-- SELECT * FROM emp WHERE DEPTNO =30 ORDER BY SAL;
-- SELECT * FROM emp ORDER BY JOB,SAL DESC;
-- SELECT DISTINCT JOB FROM emp ORDER BY JOB;
-- SELECT ENAME,DNAME FROM dept INNER JOIN emp ON DEPT.DEPTNO = EMP.DEPTNO WHERE emp.ENAME = 'ALLEN';
-- SELECT DNAME,ENAME,JOB,SAL FROM emp,dept ORDER BY DNAME,SAL DESC;
-- SELECT ENAME,SAL,COMM,SAL + COMM FROM emp WHERE JOB = 'SALESMAN';
-- SELECT ENAME,JOB,DATE_FORMAT(HIREDATE,"%D %M %Y") FROM emp WHERE DEPTNO =20;
--	SELECT DEPTNO,MAX(SAL) FROM emp GROUP BY DEPTNO;
-- SELECT DEPTNO,SUM(SAL),COUNT(EMPNO),AVG(SAL) FROM emp GROUP BY DEPTNO;
-- SELECT DEPTNO,SUM(SAL),COUNT(EMPNO),AVG(SAL) FROM emp GROUP BY DEPTNO;
-- SELECT DEPTno,SUM(SAL),COUNT(EMPNO),AVG(SAL) FROM emp GROUP BY DEPTNO HAVING COUNT(EMPNO) >2;
-- SELECT ENAME,DNAME,SAL FROM emp INNER JOIN dept ON emp.deptno=dept.DEPTNO WHERE emp.job =(SELECT JOB FROM emp WHERE ENAME ='JONES') AND ename <>'jones';
-- UPDATE emp SET PROJNO = CASE WHEN JOB='SALESMAN' AND DEPTNO=30 THEN 101 ELSE 102 END;

-- ALTER TABLE projet ADD CONSTRAINT pk_projet PRIMARY KEY CLUSTERED (projno);
-- ALTER TABLE emp ADD CONSTRAINT fk_emp_proj FOREIGN KEY (PROJNO) REFERENCES projet(PROJNO);

-- SELECT ENAME,JOB,DNAME,PROJNOM FROM emp INNER JOIN dept ON dept.DEPTNO = emp.DEPTNO INNER JOIN projet ON emp.PROJNO = projet.PROJNO;
-- SELECT ENAME,JOB,DNAME,PROJNOM FROM emp INNER JOIN dept ON dept.DEPTNO = emp.DEPTNO INNER JOIN projet ON emp.PROJNO = projet.PROJNO ORDER BY DNAME, PROJNOM;
-- SELECT PROJNOM,JOB FROM emp INNER JOIN dept ON dept.DEPTNO = emp.DEPTNO INNER JOIN projet ON emp.PROJNO =projetemp projet.PROJNO WHERE job='MANAGER';