-- ALTER TABLE emp ADD CONSTRAINT fk_mgr_empno FOREIGN KEY (MGR) REFERENCES emp (EMPNO);
-- ALTER TABLE emp ADD CONSTRAINT fk_deptno_empno FOREIGN KEY (DEPTNO) REFERENCES dept(DEPTNO);

-- UPDATE emp SET ENAME='ALLEN' WHERE EMPNO = 7499;

-- SELECT ENAME,JOB,EMPNO,SAL FROM emp WHERE DEPTNO =10;
-- SELECT ENAME,JOB,EMPNO,SAL FROM emp WHERE JOB='MANAGER' and SAL>2800;
-- SELECT JOB FROM emp WHERE DEPTNO !=30;
-- SELECT * FROM emp WHERE SAL BETWEEN 1200 AND 1400;
--	SELECT * FROM emp  WHERE DEPTNO IN(10,30) ORDER BY ENAME;
-- SELECT * FROM emp WHERE DEPTNO =30 ORDER BY SAL;
-- SELECT * FROM emp ORDER BY JOB,SAL DESC;
-- SELECT DISTINCT JOB FROM emp ORDER BY JOB;
-- SELECT DNAME FROM dept INNER JOIN emp ON DEPT.DEPTNO = EMP.DEPTNO WHERE emp.ENAME = 'ALLEN';
-- SELECT DNAME,ENAME,JOB,SAL FROM emp,dept ORDER BY DNAME,SAL DESC;
-- SELECT ENAME,SAL,COMM,SAL + COMM FROM emp WHERE JOB = 'SALESMAN';
-- SELECT ENAME,JOB,DATE_FORMAT(HIREDATE,"%D %M %Y") FROM emp WHERE DEPTNO =20;
--	SELECT DEPTNO,MAX(SAL) FROM emp GROUP BY DEPTNO;
-- SELECT DEPTno,SUM(SAL),COUNT(EMPNO),AVG(SAL) FROM emp GROUP BY DEPTNO;
-- SELECT DEPTno,SUM(SAL),COUNT(EMPNO),AVG(SAL) FROM emp GROUP BY DEPTNO;

